apiVersion: apps/v1
kind: Deployment
metadata:
  name: troublepod-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: troublepod
  template:
    metadata:
      labels:
        app: troublepod
    spec:
      containers:
      - name: trouble-container
        image: nginx:invalid-tag  # Intentional error - invalid image tag
        ports:
        - containerPort: 80
        livenessProbe:            # Configured to fail
          httpGet:
            path: /nonexistent    # Wrong path
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:           # 3. Will fail (wrong port)
          httpGet:
            path: /               # Correct path
            port: 8080           # Wrong port (should be 80)
          initialDelaySeconds: 3
          periodSeconds: 3
        resources:
          limits:
            memory: "50Mi"       # Very low memory limit (likely to cause OOM)
